# -*- coding: utf-8 -*-
"""weather_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNO0j5yZTX1KjRKX5Isq1eqNiEGvUJG4

## statements in python
"""

#           real wheather dataset

import pandas as pd

data = pd.read_csv("weather data.csv")               #read or load data from csv file
data

data.head()

data.tail()

data.shape

data.index            #it will show +1 at stop

data.columns

data.dtypes

data["Weather"].unique()           #unique command used for a particular column

data.nunique()

data.count

data.value_counts()

data["Weather"].value_counts()

data.info()

#q1)find all the unique "wind speed" values in the data.

data.nunique()

data["Wind Speed_km/h"].nunique()

data["Wind Speed_km/h"].unique()       #ans 1.

#q2)   find the number of times when the weather is exactly clear?

# there are three ways in which we will solve this problem
 #value_counts()
 #Filtering
 #groupby

data.Weather.value_counts()

#filtering

data.head(2)
data[data.Weather=="Clear"]

#groupby
data.head(2)
data.groupby("Weather").get_group("Clear")

# Q3) Find the number of times when the "wind speed was exactly 4km/h" ?

data.head(2)

data[data["Wind Speed_km/h"]==4]

# Q4) find out all the null values in the data?

data.head(1)

data[data.isnull()].nunique()

data.isnull().sum()

data.notnull().sum()

# Q5) Rename the column name "Weather" of the dataframe to "Weather Condition".

data.rename(columns={"Weather":"Weather Condition"},inplace=True)       #this will rename column temporarly so if we want to replace it parmanently use this command:-   },inplace=True

# Q6) What is the mean "Visibility"?

data.describe()

data.Visibility_km.mean()

#Q7) What is the "Standard Deviation" of "pressure" in this data

data.Press_kPa.std()

# Q8) what is the variance of "Relative Humidity" in this data?

import numpy as np
data["Rel Hum_%"].var()

# Q9) Find all instances when "snow" was recorded?

data["Weather Condition"].value_counts()

data[data["Weather Condition"]=="Snow"]

# Q 10) find all the instances when "Wind Speed" is above 24 and "Visibility" is 25 ?

data.head(2)

data[(data["Visibility_km"]==25) & (data['Wind Speed_km/h']>24)]

data[(data.Visibility_km==25) & (data["Wind Speed_km/h"]>24)]

data[(data["Visibility_km"]==25) & (data['Wind Speed_km/h']>24)].value_counts()

# Q.11) What is the Mean value of each column against each "Weather Condition"?

data.head(2)

data.groupby("Weather Condition").mean()

# Q 12) What is the minimum and maximum value of column against each 'Weather Condition' ?

data.head(2)

data.groupby("Weather Condition").min()

data.groupby("Weather Condition").max()

# Q.13) Show all the records where Weather Condition is Fog ?

data.head()

data[data["Weather Condition"]=="Fog"]



# Q.14) Find all the instances when "Weather is Clear" or "Visibility is above 40 " ?

data.head(2)

data[(data['Weather Condition']=="Clear") | (data['Visibility_km']>40)]

